/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacyManagement;

import Doctor.Doctor;
import Login.Login;
import Patient.Patient;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

/**
 *
 * @author DR.LAP
 */
public class pharmacyManagement extends javax.swing.JFrame {
    
    /**
     * Creates new form pharmacyManagement
     */
    public pharmacyManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        refNo = new javax.swing.JTextField();
        lot = new javax.swing.JTextField();
        IssDate = new javax.swing.JTextField();
        ExpDate = new javax.swing.JTextField();
        DailyDos = new javax.swing.JTextField();
        dosetf = new javax.swing.JTextField();
        NumOfTab = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        SideEff = new javax.swing.JTextField();
        FurthInf = new javax.swing.JTextField();
        HTU = new javax.swing.JTextField();
        PatID = new javax.swing.JTextField();
        docnhs = new javax.swing.JTextField();
        StoreAdv = new javax.swing.JTextField();
        Admins = new javax.swing.JTextField();
        NameTablets = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        ex = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pharmacy");
        setPreferredSize(new java.awt.Dimension(1050, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("LOT:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Daily Dose:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("Exp. Date:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setText("Issued Date:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 153));
        jLabel5.setText("Number Of Tablets:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 153));
        jLabel6.setText("Reference no.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 153));
        jLabel7.setText("Name Of Tabelts:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 153));
        jLabel8.setText("Dose (mg):");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        refNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        refNo.setForeground(new java.awt.Color(0, 51, 102));
        refNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refNoActionPerformed(evt);
            }
        });
        getContentPane().add(refNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 160, -1));

        lot.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lot.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(lot, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 160, -1));

        IssDate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        IssDate.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(IssDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 160, -1));

        ExpDate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ExpDate.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(ExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 160, -1));

        DailyDos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DailyDos.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(DailyDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 160, -1));

        dosetf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dosetf.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(dosetf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 160, -1));

        NumOfTab.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NumOfTab.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(NumOfTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 160, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 0, 153));
        jLabel17.setText("How To Use:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 0, 153));
        jLabel19.setText("Doctor NHS no.:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 0, 153));
        jLabel20.setText("Patient ID:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 0, 153));
        jLabel21.setText("Administration:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 0, 153));
        jLabel22.setText("Side Effects:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 0, 153));
        jLabel23.setText("Further Informarion:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 0, 153));
        jLabel24.setText("Storage Advice:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        SideEff.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SideEff.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(SideEff, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 160, -1));

        FurthInf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        FurthInf.setForeground(new java.awt.Color(0, 51, 102));
        FurthInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FurthInfActionPerformed(evt);
            }
        });
        getContentPane().add(FurthInf, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 160, -1));

        HTU.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        HTU.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(HTU, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 160, -1));

        PatID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PatID.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(PatID, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 160, -1));

        docnhs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        docnhs.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(docnhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 160, -1));

        StoreAdv.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        StoreAdv.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(StoreAdv, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 160, -1));

        Admins.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Admins.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(Admins, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 160, -1));

        NameTablets.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NameTablets.setForeground(new java.awt.Color(0, 51, 102));
        NameTablets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Panadol", "Paracetamol", "Insulin", "Acetaminophen" }));
        NameTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(NameTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 160, -1));

        jPanel3.setBackground(new java.awt.Color(251, 232, 251));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(251, 232, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 153));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 0, 153));
        jButton4.setText("Doctor");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 110, -1));

        jButton8.setBackground(new java.awt.Color(153, 153, 153));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(153, 0, 153));
        jButton8.setText("Patient");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 90, -1));

        ex.setBackground(new java.awt.Color(153, 153, 153));
        ex.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ex.setForeground(new java.awt.Color(153, 0, 153));
        ex.setText("Exit");
        ex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exActionPerformed(evt);
            }
        });
        jPanel1.add(ex, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 90, -1));

        jButton12.setBackground(new java.awt.Color(153, 153, 153));
        jButton12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(153, 0, 153));
        jButton12.setText("Login");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 90, -1));

        jButton6.setBackground(new java.awt.Color(153, 153, 153));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 0, 153));
        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 670, 70));

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(153, 0, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of tablet", "Ref No.", "Dose", "Num of tab", "LOT", "Issued Date", "Exp Date", "Daily Dose", "Side Effects", "Fur Info", "Storage Advice", "Administration", "How to use", "Patient ID", "Doc. NHS"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 910, 240));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 1500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refNoActionPerformed

    private void FurthInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FurthInfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FurthInfActionPerformed

    //Panadol, Paracetamol, Insulin, Acetaminophen
    private void NameTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTabletsActionPerformed
       
        if(NameTablets.getSelectedItem().equals("Panadol")){
         refNo.setText("006Pan");
         Admins.setText("Yes, actioned");
         DailyDos.setText("4");
         ExpDate.setText("21/01/2022"); 
         FurthInf.setText("Keep away from children");
         HTU.setText("With Water");
         String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(Calendar.getInstance().getTime());
         IssDate.setText(timeStamp);
         NumOfTab.setText("32");
         //PatID.setText("");
         SideEff.setText("no side effects");
         StoreAdv.setText("room temperature");
         //docnhs.setText("006Pan");
         dosetf.setText("2");
         lot.setText("006555");
         
       }
       
       
       if(NameTablets.getSelectedItem().equals("Paracetamol")){
         refNo.setText("007Parac");
         Admins.setText("Yes, actioned");
         DailyDos.setText("2");
         ExpDate.setText("21/01/2022"); 
         FurthInf.setText("Keep away from children");
         HTU.setText("with water");
         String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(Calendar.getInstance().getTime());
         IssDate.setText(timeStamp);
         NumOfTab.setText("44");
         //PatID.setText("006Pan");
         SideEff.setText("Bloody or cloudy urine");
         StoreAdv.setText("room temperature");
         //docnhs.setText("006Pan");
         dosetf.setText("1");
         lot.setText("0073333");
         
       }
       
       
       if(NameTablets.getSelectedItem().equals("Insulin")){
         refNo.setText("002Ins");
         Admins.setText("Yes, Actioned");
         DailyDos.setText("2");
         ExpDate.setText("21/01/2022"); 
         FurthInf.setText("Keep away from children");
         HTU.setText("Pinch the skin and put the needle in at a 45º angle");
         String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(Calendar.getInstance().getTime());
         IssDate.setText(timeStamp);
         NumOfTab.setText("5 mg");
         //PatID.setText("006Pan");
         SideEff.setText("Swelling of your arms and legs");
         StoreAdv.setText("cold place");
         //docnhs.setText("006Pan");
         dosetf.setText("5 mg");
         lot.setText("002442");
         
       }
       
       if(NameTablets.getSelectedItem().equals("Acetaminophen")){
         refNo.setText("008Ace");
         Admins.setText("Yes, Actioned");
         DailyDos.setText("2");
         ExpDate.setText("21/01/2022"); 
         FurthInf.setText("Keep away from children");
         HTU.setText("with water");
         String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(Calendar.getInstance().getTime());
         IssDate.setText(timeStamp);
         NumOfTab.setText("32");
         //PatID.setText("006Pan");
         SideEff.setText("Nausea, vomiting, loss of appetite, or severe stomach pain");
         StoreAdv.setText("Room Temperature");
         //docnhs.setText("006Pan");
         dosetf.setText("1");
         lot.setText("008779");
         
       }
    }//GEN-LAST:event_NameTabletsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
      if(jTable1.getSelectedRow()==-1)
      {
         if(jTable1.getRowCount()==0)
         {
          JOptionPane.showMessageDialog(null, "no data to delete", "Pharmacy Management System", 
          JOptionPane.OK_OPTION);
         }
         else
         {
          JOptionPane.showMessageDialog(null, "Select a row to delete", "Pharmacy Management System", 
          JOptionPane.OK_OPTION);
         }
      
     }
      
      else
      {
        model.removeRow(jTable1.getSelectedRow());
      
      }
    }//GEN-LAST:event_jButton2ActionPerformed
   

    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       
       model.addRow(new Object[] {NameTablets.getSelectedItem().toString(),refNo.getText(),
           dosetf.getText(),NumOfTab.getText(),lot.getText(), IssDate.getText() , ExpDate.getText(),DailyDos.getText() , 
           SideEff.getText() ,FurthInf.getText(),StoreAdv.getText(), Admins.getText(),HTU.getText() , PatID.getText() , 
           docnhs.getText() });
    }//GEN-LAST:event_jButton6ActionPerformed

     private JFrame frame2;
    private void exActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exActionPerformed
     frame2 = new JFrame("Exit");
     if(JOptionPane.showConfirmDialog(frame2,"Are you sure you want to exit" , "Pharmacy Management System",
         JOptionPane.YES_NO_OPTION )== JOptionPane.YES_NO_OPTION){
         System.exit(0);
     }
    }//GEN-LAST:event_exActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
       Login log = new Login();
       log.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Doctor dr = new Doctor();
        dr.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Patient pat = new Patient();
        pat.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed
   
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pharmacyManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pharmacyManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pharmacyManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pharmacyManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pharmacyManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Admins;
    private javax.swing.JTextField DailyDos;
    private javax.swing.JTextField ExpDate;
    private javax.swing.JTextField FurthInf;
    private javax.swing.JTextField HTU;
    private javax.swing.JTextField IssDate;
    private javax.swing.JComboBox<String> NameTablets;
    private javax.swing.JTextField NumOfTab;
    private javax.swing.JTextField PatID;
    private javax.swing.JTextField SideEff;
    private javax.swing.JTextField StoreAdv;
    private javax.swing.JTextField docnhs;
    private javax.swing.JTextField dosetf;
    private javax.swing.JButton ex;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lot;
    private javax.swing.JTextField refNo;
    // End of variables declaration//GEN-END:variables
}
