/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Doctor.Doctor;
import Patient.Patient;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pharmacyManagement.pharmacyManagement;

/**
 *
 * @author DR.LAP
 */
public class Login extends javax.swing.JFrame {
    
     int attempts = 0;
    /**
     * Creates new form Login
     */
    public Login() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usr = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        lgn1 = new javax.swing.JButton();
        ext = new javax.swing.JButton();
        cncl = new javax.swing.JButton();
        dr = new javax.swing.JButton();
        ph = new javax.swing.JButton();
        ptnt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pharmacy Management");
        setBackground(new java.awt.Color(204, 255, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(204, 204, 0));
        setName("Pharmacy Management"); // NOI18N
        setPreferredSize(new java.awt.Dimension(880, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(251, 232, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        usr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        usr.setForeground(new java.awt.Color(0, 51, 102));
        usr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(usr, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 210, -1));

        Password.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(0, 51, 102));
        Password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 210, 30));

        lgn1.setBackground(new java.awt.Color(153, 153, 153));
        lgn1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lgn1.setForeground(new java.awt.Color(153, 0, 153));
        lgn1.setText("Login");
        lgn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgn1ActionPerformed(evt);
            }
        });
        jPanel1.add(lgn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 120, 30));

        ext.setBackground(new java.awt.Color(153, 153, 153));
        ext.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ext.setForeground(new java.awt.Color(153, 0, 153));
        ext.setText("Exit");
        ext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extActionPerformed(evt);
            }
        });
        jPanel1.add(ext, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 120, 30));

        cncl.setBackground(new java.awt.Color(153, 153, 153));
        cncl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cncl.setForeground(new java.awt.Color(153, 0, 153));
        cncl.setText("Cancel");
        cncl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnclActionPerformed(evt);
            }
        });
        jPanel1.add(cncl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 530, 260));

        dr.setBackground(new java.awt.Color(153, 153, 153));
        dr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dr.setForeground(new java.awt.Color(153, 0, 153));
        dr.setText("Doctor");
        dr.setBorder(null);
        dr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drActionPerformed(evt);
            }
        });
        getContentPane().add(dr, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 200, 40));

        ph.setBackground(new java.awt.Color(153, 153, 153));
        ph.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ph.setForeground(new java.awt.Color(153, 0, 153));
        ph.setText("Pharmacy");
        ph.setBorder(null);
        ph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phActionPerformed(evt);
            }
        });
        getContentPane().add(ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 200, 40));

        ptnt.setBackground(new java.awt.Color(153, 153, 153));
        ptnt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ptnt.setForeground(new java.awt.Color(153, 0, 153));
        ptnt.setText("Patient");
        ptnt.setBorder(null);
        ptnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptntActionPerformed(evt);
            }
        });
        getContentPane().add(ptnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 200, 40));

        jPanel2.setBackground(new java.awt.Color(251, 232, 251));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Pharmacy Management System");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 510, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 610, 100));

        jPanel3.setBackground(new java.awt.Color(251, 232, 251));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 1500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private JFrame frame;
    private void extActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extActionPerformed
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Are you sure you want to exit" , "Pharmacy Management System",
                JOptionPane.YES_NO_OPTION )== JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_extActionPerformed

    private void ptntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptntActionPerformed
        Patient pat = new Patient();
        pat.setVisible(true);
    }//GEN-LAST:event_ptntActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
                  dr.setEnabled(false);
                 
                  ph.setEnabled(false);
                  ptnt.setEnabled(false);
                  
      
    }//GEN-LAST:event_formWindowActivated

    private void cnclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnclActionPerformed
        usr.setText("");
        Password.setText("");
    }//GEN-LAST:event_cnclActionPerformed
       
    private void lgn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgn1ActionPerformed
        String username = usr.getText();
        String pass = Password.getText();
        
        if (username.contains("one") && pass.contains("one"))
        {
            usr.setText("");
            Password.setText("");
            dr.setEnabled(true);
           
            ph.setEnabled(true);
            ptnt.setEnabled(true);
           
         }
        
        else if (!(username.contains("one") && pass.contains("one")))
                { 
                  usr.setText("");
                  Password.setText("");  
                  dr.setEnabled(false);
                 
                  ph.setEnabled(false);
                  ptnt.setEnabled(false);
                
                  
                  attempts += 1;
                  
                  if(attempts == 3)
                  {
                    System.exit(0);
                  }
                }
    }//GEN-LAST:event_lgn1ActionPerformed

    private void phActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phActionPerformed
        pharmacyManagement pharmacy = new pharmacyManagement();
        pharmacy.setVisible(true);
    }//GEN-LAST:event_phActionPerformed

    private void drActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drActionPerformed
        Doctor dr = new Doctor();
        dr.setVisible(true);
    }//GEN-LAST:event_drActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton cncl;
    private javax.swing.JButton dr;
    private javax.swing.JButton ext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton lgn1;
    private javax.swing.JButton ph;
    private javax.swing.JButton ptnt;
    private javax.swing.JTextField usr;
    // End of variables declaration//GEN-END:variables
}
